# Generated by Django 5.1.6 on 2025-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=30)),
                ('made_in', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('for_what', models.TextField(blank=True)),
                ('use_instruction', models.TextField()),
                ('made_date', models.DateField()),
                ('expiration_date', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pill_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
